[workspace]
members = [
  "yew",
  "yew-components",
  "yew-functional",
  "yew-macro",
  "yew-validation",

  # Router
  "yew-router",
  "yew-router-macro",
  "yew-router-route-parser",
  "yew-router/examples/minimal",
  "yew-router/examples/router_component",
  "yew-router/examples/switch",

  # Utilities
  "yewtil",
  "yewtil-macro",
  "yewtil/examples/fetch",
  "yewtil/examples/lrc",
  "yewtil/examples/mrc_irc",

  # dsl
  "yew-dsl",

  # Examples
  "examples/ccxt_and_gravatar",
  "examples/counter",
  "examples/crm",
  "examples/custom_components",
  "examples/dashboard",
  "examples/file_upload",
  "examples/fragments",
  "examples/futures",
  "examples/game_of_life",
  "examples/inner_html",
  "examples/js_callback",
  "examples/keyed_list",
  "examples/mount_point",
  "examples/multi_thread",
  "examples/nested_list",
  "examples/node_refs",
  "examples/pub_sub",
  "examples/store",
  "examples/timer",
  "examples/todomvc",
  "examples/two_apps",
  "examples/webgl",
  "examples/boids",
]
