[package]
name = "router"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]
edition = "2018"

[dependencies]
lipsum = "0.7"
log = "0.4"
rand = { version = "0.7", features = ["small_rng", "wasm-bindgen"] }
wasm-logger = "0.2"
yew = { path = "../../yew" }
yew-router = { path = "../../yew-router" }
yewtil = { path = "../../yewtil" }
